### PR TITLE
Provide consistent semantics for composite "wait" operations when no coroutines are provided.

### LINKED ISSUE #3: Recoil::all() does not handle empty arrays
Using `yield [];` in a coroutine results in
```
Recoil\Kernel\Exception\KernelStoppedException: The kernel was stopped before the main strand exited.
```
and its traceback doesn't point to the code that caused this.

I think `yield [];` should be equivalent to `yield;` or return immediately or, alternatively, a mention in the docs be made.

(I'm using React kernel.)

Thank you for your work.

### PR DESCRIPTION
**Pull request by jmalloc**
Fixes #3

### CODE REVIEW

File: src/ApiTrait.php [hunk 1]
```diff
@@ -34,16 +34,16 @@
     public function __dispatch(SystemStrand $strand, $key, $value)
```
Comment (koden-km) [inline src/ApiTrait.php:36]: This method is not declaring any return type, yet it is now returning something.
Not all paths specifically return anything.

Comment (jmalloc) [reply src/ApiTrait.php:36]: Good call, updated.

**Review by koden-km — COMMENTED** [review]
Only issue I see is the `__dispatch()` method missing a return type.
